language: r
cache: packages
sudo: false

r_packages:
 - ggplot2

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
