language: r
sudo: required
warnings_are_errors: true

r_packages:
 - ggplot2

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
